apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ffmpeg-server
  template:
    metadata:
      labels:
        app: ffmpeg-server
    spec:
      containers: 
      - image: dilio007/ffmpeg:1.1.0
        name: ffmpeg-se
        ports:
        - containerPort: 8080

